from frappe.custom.doctype.custom_field.custom_field import create_custom_field


def execute():
    create_custom_field(
        "File",
        {
            "default": "0",
            "fieldname": "generated_by_genie",
            "read_only": 1,
            "fieldtype": "Check",
            "label": "Generated by Genie",
            "insert_after": "uploaded_to_google_drive"
        }
    )
